### ISSUE TITLE
Chrome throws 500 on login button press

### ISSUE THREAD

**Issue by nymd** [pokt-foundation/portal#133]
When attempting to login using Chrome, the login button throws a 500 error in console.

**To Reproduce**
1. Load Chrome
2. Go to home page, attempt to login

![image](https://user-images.githubusercontent.com/16605170/120824576-71d58f00-c50d-11eb-8806-9db307c01538.png)

**Desktop (please complete the following information):**
 - Ubuntu 18, Chrome latest

Logs here:
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E0$257Estart$257E-3600$257EtimeType$257E$2527RELATIVE$257Eunit$257E$2527seconds$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*20200$257EisLiveTail$257Efalse$257EqueryId$257E$252719679161-a9af-4e68-a06e-f35ce701a25d$257Esource$257E$2528$257E$2527*2fecs*2fdashboard-mainnet-backend$2529$2529

**Comment by Evalir** [comment]
Quickly tested on Chrome and wasn't able to reproduce this. Could you try again @nymd ?

**Comment by nymd** [comment]
![image](https://user-images.githubusercontent.com/16605170/121077633-b9b61980-c78c-11eb-85fc-b3450aaf2746.png)

entered: alex@example.org
pass: 123123

result: 500 Internal Server

**Comment by nymd** [comment]
@Evalir

**Comment by Evalir** [comment]
Reopening due to newly reported issues on signups/logins.

**Comment by Evalir** [comment]
Closed with #153. Finally!
