### ISSUE TITLE
Pull BaseRelaysPerPOKT information from on-chain data rather than Github Secrets

### ISSUE THREAD

**Issue by nymd** [pokt-foundation/portal#166]
Currently the Relays per POKT formula is stored in Github Secrets. When this value is updated by the DAO or the executives, the Portal's value must be changed immediately.

This presents possible issues with fat-fingering and delayed updates of this value. 

To improve the data consistency, this value should be pulled from the on-chain value:

> pocket query params

```
"app_params": [
        {
            "param_key": "application/BaseRelaysPerPOKT",
            "param_value": "526"
        },
```

```
o_rourke — Today at 10:26 AM
the denominator is 100
so 52.6 per session
Enrique — Today at 10:26 AM
Gotcha, so that's 526 relays/day
o_rourke — Today at 10:26 AM
52.6 * 24 = relays a day
```

**Comment by Evalir** [comment]
For future reference, we don't use any of these environment variables anymore regarding the chain. The only thing we do use is the amount of POKT that will be staked.

**Comment by nymd** [comment]
Where is it currently stored?

**Comment by Evalir** [comment]
With Gigastakes, this is not longer needed.
