### ISSUE TITLE
Unverified email error is not shown when attempting to login

### ISSUE THREAD

**Issue by nymd** [pokt-foundation/portal#167]
When logging in, if a user's email is not verified, no notice is given and the login hangs.

**To Reproduce**
1. Create a new user
2. Do not verify the email
3. Attempt to login
4. For every attempt you will receive an email notice to verify but nothing in the UI

**Expected behavior**
A UI notice should be shown telling the user to verify their email before logging in.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - FF, latest

**Comment by Evalir** [comment]
Closed with #168
