### ISSUE TITLE
Pocket Network Polygon-Grants Hackathon- Integrate a Pocket-powered Endpoint into your DApp 

### ISSUE THREAD

**Issue by RichardJamesLopez** [pokt-foundation/portal#247]
### Pocket Network - Integrate an RPC Endpoint Minted from the Pocket Portal into your DApp
**Prize Bounty**
- 6000 of USDT

- 1st Place = 2500 USDT
- 2nd Place = 1500 USDT
- 3rd, 4th, 5th, & 6th  Place = 500 USDT

**Challenge Description**
Every DApp needs blockchain data. [Pocket Network](https://bit.ly/PocketPortalPolygonHackathon) provides the full spectrum of blockchain data in a decentralized, censorship-resistant manner. The [Pocket Portal](https://bit.ly/PocketPortalPolygonHackathon) makes it easy to mint an RPC endpoint for any of the blockchains Pocket supports in just a few clicks.

These are the networks available within the [Pocket Portal](https://bit.ly/PocketPortalPolygonHackathon) to use in your application:

- Polygon Mainnet
- Polygon Archival
- Ethereum Mainnet
- Ethereum Mainnet Archival
- Ethereum Mainnet Archival with Tracing
- Ethereum Testnet Goerli
- Ethereum Testnet Kovan
- xDAI
- Avalanche
- Fuse Mainnet
- Binance Smart Chain (Archival)

We want you to use Pocket Network as your decentralized blockchain data provider for any of the blockchains listed above.

**Submission Requirements**

- Mint an RPC Endpoint for your desired blockchain network from the Pocket Portal
- Integrate the RPC Endpoint into your DApp
- Demonstrate usage
- Code should be available for the Pocket judge to review
- Demo or Demo Video strongly recommended

**Judging Criteria**

- Integrates an RPC Endpoint minted from the Pocket Portal
- Creativity of the dApp
- Utility of the dApp

Deadline for Submissions
Oct 29th at 10AM EST

**Winner Announcement Date**
TBD

**Resources**

- Mint an RPC Endpoint from the [Pocket Portal](https://bit.ly/PocketPortalPolygonHackathon)
- Here's a [quick setup guide on how to use the Pocket Portal](https://docs.pokt.network/home/paths/app-developer)
- Here's a [video walk through of the Pocket Portal](https://www.youtube.com/watch?v=cULknE1xPR4)
- Link to our [Discord](https://discord.com/invite/rUt8UerC5W)

**Comment by siriusbeans** [comment]
Hello, I would like to participate in this bounty.  Would the Pokt.Network team be willing to also include the Ethereum Rinkeby Testnet chain as an acceptable RPC Endpoint option for this bounty?

**Comment by RichardJamesLopez** [comment]
> Hi! We are planning to pick this. We will be building a gaming Dapp powered by the pocket portal RPC endpoint. We will be hosting this service for demo purposes, attach working screenshots and post a link to the demo video.

Awesome @wilbert69. Let us know if we can answer questions in the interim. We have a channel in the Polygon discord.

**Comment by ereid7** [comment]
@RichardJamesLopez 

Hello! I have created a Pull Request to submit, however I do not have the rights to attach this issue. 
https://github.com/pokt-foundation/portal/pull/289

Here is the project I am submitting:
https://github.com/ereid7/dblog-dapp

Here is a youtube video demonstrating my submission:
https://www.youtube.com/watch?v=RpCy5lOF6yk

**Comment by RichardJamesLopez** [comment]
> @RichardJamesLopez
> 
> Hello! I have created a Pull Request to submit, however I do not have the rights to attach this issue. #289
> 
> Here is the project I am submitting: https://github.com/ereid7/dblog-dapp
> 
> Here is a youtube video demonstrating my submission: https://www.youtube.com/watch?v=RpCy5lOF6yk
> 
> Since I cannot link this issue to my PR, I am not sure how to link my wallet on hackerlink. Let me know if there is anything else I should do to complete my submission.

Nice. Let me see best way to submit. We have it on our record as a submission so rest assured it will be taken care of.

**Comment by RichardJamesLopez** [comment]
> I will be making a submission. Will join you on Discord. How do I submit my dapp?

Hi @shopglobal !

You can submit the details like above when @ereid7 commented in this Github page. We'll take care of the rest.

**Comment by siriusbeans** [comment]
> 
> 
> > Hello, I would like to participate in this bounty. Would the Pokt.Network team be willing to also include the Ethereum Rinkeby Testnet chain as an acceptable RPC Endpoint option for this bounty?
> 
> Hey @siriusbeans . ETH Rinkeby would be 100% good for this bounty.

Ok, @RichardJamesLopez , here is my submission:  https://github.com/nocturnal-finance

Rinkeby UI:  https://nocturnal.finance

**Comment by deman41191** [comment]
Awesome

**Comment by Caner344** [comment]
Güzel proje
